local L = LibStub("AceLocale-3.0"):NewLocale("dna", "enUS", true, true)
if not L then return end
--*****************************************************
--GUI Localization
--*****************************************************
L["common/dna"]				= "dna"
L["common/LDB/tt1"] 			= "<Right Click> to open dna"
L["common/LDB/tt2"] 			= "<Left Click> to select a Rotation"
L["common/versionprefix"]		= "v"

L["utils/debug/prefix"] 		= "|cffF95C25dna|r:"
L["utils/debug/mlebDebug/l"] 	= "Debug Output:"
L["utils/debug/lua/l"]		 	= "Lua compiler:"

L["maintree/options"] 	= "Options"
L["maintree/lists"] 	= "Lists"
L["maintree/rotations"] = "Rotations"

L["common/clear"]								= "Clear"
L["common/delete"]								= "Delete"
L["common/done"]								= "Done"
L["common/test"]								= "Test"
L["common/none"]								= "None"
L["common/yes"]									= "Yes"
L["common/no"]									= "No"
L["common/ctrlc"]								= "Press Ctrl+C to copy to clipboard"
L["common/help"]								= "|cffF95C25dna commands:|r\n|cffF95C25/dna|r - toggles the dna config window\n|cffF95C25/dna resetscale|r - resets ui scale to 1\n|cffF95C25/dna rotationname|r - changes current rotation to rotationname\n"

L["common/error/exists"]						= "Error: %s already exists."
L["common/error/dnexist"]						= "Error: %s does not exist."
L["common/error/unsafestring"]					= "Error: %s cannot be blank or contain the nested squences [=[ or ]=]"
L["common/error/numbers"]						= "Error: %s cannot contain only numbers"
L["common/error/renamedefault"]					= "Error: %s is a default and cannot be renamed"
L["common/error/spellnotfoundwh"]				= "Error: %s spell not found. Try using spell id from Wowhead."
L["common/error/itemnotfoundwh"]				= "Error: %s item not found. Try using item id from Wowhead."
-- L["common/error/anchor1"]						= "Cannot move anchor in combat"
-- L["common/error/anchor2"]						= "Use ElvUI to move the dna anchor"
L["common/error/deleteincombat"]				= "Cannot delete in combat"
L["common/error/priorityincombat"]				= "Cannot change priority in combat"
L["common/error/keybindincombat"]				= "Cannot keybind in combat"
L["common/hotkey/l"]							= "HotKey:"
L["common/chatinfo/initcomplete"]				= "Initialization complete."
L["common/chatwarn/initpending"]				= "Initialization pending, please leave combat to allow initialization."
L["common/spellid/l"]							= "SpellID:"
L["common/spellid/tt"]							= "Enter global spellID"
L["common/spellname/l"]							= "SpellName:"
L["common/spellname/tt"]							= "Enter SpellName |cffF95C25Brain Freeze|r"
L["common/spellname/dv"]							= ""
--*****************************************************
--Options Panel
--*****************************************************
L["options/cbPrintHighestPriority/l"]			= "Print highest priority action to chat window"

--*****************************************************
--Lists Panel
--*****************************************************
L["lists/ebListName/l"]							= "New List:"
L["lists/mlebListImport/l"]						= "List Import (Ctrl+V):"

--*****************************************************
--List Panel
--*****************************************************
L["list/ebListExport/l"]						= "List Export (Ctrl+C):"
L["list/ebListExport/tt"]						= "Press the export button then Ctrl+C,Ctrl+V to share this list in a forum"
L["list/bListExport/l"]							= "Export"
L["list/bListExport/tt"]						= "Click to export 1 line format\nShift+click to export script format\nAlt+click to export forum format"
L["list/ebShareListExport/l"]					= "Share List:"
L["list/ebShareListExport/tt"]					= "Enter the name of the player to send list to:\n|cffF95C25Playername|r or\n|cffF95C25Playername-RealmNoSpaces|r"
L["list/ebRenameList/l"]						= "Rename List:"
L["list/ebRenameList/tt"]						= "Enter new list name and press ENTER"
L["list/ebAddSpellEntry/l"]						= "New Spell Entry:"
L["list/ebAddSpellEntry/tt"]					= "Enter spell name, spellID or spellLink and press ENTER to add to this list"
L["list/ebAddItemEntry/l"]						= "New Item Entry:"
L["list/ebAddItemEntry/tt"]						= "Enter item name, itemID or itemLink and press ENTER to add to this list"
L["list/ebCopyList/l"]							= "Copy List:"
L["list/ebCopyList/tt"]							= "Enter the new list name and press ENTER to make a copy of this list"
L["list/bListDelete/tt"]						= "Delete this list\n|cffFF0000WARNING|r: No undo or prompt"
L["list/ilLMoveUp/tt"]							= "Move list up"
L["list/ilLMoveDown/tt"]						= "Move list down"
L["list/bEntryDelete/tt"]						= "Delete the selected spell from the list\n|cffFF0000WARNING|r: No undo or prompt"

--*****************************************************
--Rotations Panel
--*****************************************************
L["rotations/ebRotationName/l"]					= "New Rotation:"
L["rotations/mlebRotationImport/l"]				= "Rotation Import (Ctrl+V):"
L["rotations/importfail"]						= "Import failed:"
L["rotations/rimportfail"]						= "Rotation import failed."
L["rotations/rimportfail/E4"]					= "Action pack import failed, check to make sure the action pack is not a rotation."
L["rotations/rimportfail/E5"]					= "Rotation import failed, check to make sure the rotation is not a action pack."
L["rotations/rimportfail/E6"]					= "Rotation import failed, rotation key not found when adding actions."
L["rotations/exportfail/E1"]					= "Rotation export failed. List %s is in the old format and needs to be recreated."
L["rotations/importsuccess"]					= "Successfully imported rotation:"
L["rotations/selected"]							= "Rotation %s selected."
--*****************************************************
--Rotation Panel
--*****************************************************
L["rotation/ebRenameRotation/l"]				= "Rename Rotation:"
L["rotation/ebRenameRotation/tt"]				= "Enter new rotation name and press ENTER"
L["rotation/ebActionName/l"]					= "New Action:"
L["rotation/ebActionName/tt"]					= "Enter the new action name and press ENTER\nExample: |cffF95C25Fireball|r"
L["rotation/ebCopyRotation/l"]					= "Copy Rotation:"
L["rotation/ebCopyRotation/tt"]					= "Enter the new name and press ENTER to make a copy of this rotation\nExample: |cffF95C25[PvE] Single Target DPS|r"
L["rotation/ebRotationExport/l"]				= "Rotation Export (Ctrl+C):"
L["rotation/ebRotationExport/tt"]				= "Press the export button then Ctrl+C,Ctrl+V to share this rotation in a forum"
L["rotation/ebShareExport/l"]					= "Share Rotation:"
L["rotation/ebShareExport/tt"]					= "Enter the name of the player to send rotation to:\n|cffF95C25Playername|r or\n|cffF95C25Playername-RealmNoSpaces|r"
L["rotation/ebMeleeSpell/l"]					= "Melee Spell:"
L["rotation/ebMeleeSpell/tt"]					= "Enter a known melee spell or spellid for displaying the melee range icon|r"
L["rotation/ebRangeSpell/l"]					= "Range Spell:"
L["rotation/ebRangeSpell/tt"]					= "Enter a known ranged spell or spellid for displaying the range icon|r"
L["rotation/ddBindToSpec/l"]					= "Bind to specialization:"
L["rotation/ddBindToSpec/tt"]					= "When you change talent groups, dna will select this rotation"
L["rotation/ddEquipmentSet/l"]					= "Equipment Set:"
L["rotation/ddEquipmentSet/tt"]					= "When you change to this rotation, dna will equip this equipment set"
L["rotation/bCreate/l"]							= "Create"
L["rotation/bCreate/tt"]						= "Click to create 1 line format\nShift+click to create script format\nAlt+click to create forum format"
L["rotation/mlebActionPackImport/l"]			= "Action Pack Import:"
L["rotation/mlebActionPackImport/tt"]			= "Click in this box and press Ctrl+V to paste the action pack and press enter"
L["rotation/received/l"]						= "Rotation received from %s, do you want to import it?"
L["rotation/export/error1"]						= "Error: %s uses a non existent list %s. Check the spelling and case."
L["rotation/bExport/l"]							= "Export"
L["rotation/bExport/tt"]						= "Click to export 1 line format\nShift+click to export script format\nAlt+click to export forum format"
L["rotation/ilRMoveUp/tt"]						= "Move Rotation up in the tree"
L["rotation/ilRMoveDown/tt"]					= "Move Rotation down in the tree"
L["rotation/bRotationKeybind/l"]				= "Not Bound"
L["rotation/bRotationKeybind/tt"]				= "Bind a key to select this rotation"
L["rotation/bRotationDelete/tt"]				= "Delete this rotation\n|cffFF0000WARNING|r: No undo or prompt"
L["rotation/actionpackimportsuccess"]			= "Successfully imported action pack: "

--*****************************************************
--Action Panel
--*****************************************************
L["action/labelLineNumbers/l"]						= "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"
L["action/mlebCriteria/l"]						= "Criteria:"
L["action/ebArg/l"]								= "Arg"
L["action/bCriteriaAnd/l"]						= "And"
L["action/bCriteriaOr/l"]						= "Or"
L["action/bCriteriaNot/l"]						= "Not"
--L["action/ddActionType/l"]						= "Action Type:"
--L["action/ddActionType/tt"]						= "Select the action type"
--L["action/actiontypes/spell"]					= "Spell"
--L["action/actiontypes/macro"]					= "Macro"
--L["action/actiontypes/macrotext"]				= "MacroText"
--L["action/actiontypes/item"]					= "Item"
L["action/mlebActionTypeAtt1/l"]				= "Attribute1:"
L["action/mleditbox/spell/att1tt"]				= "Enter the unit to cast on\n|cffF95C25target\nplayer\npet|r"
L["action/mleditbox/macro/att1tt"]				= "Enter the Macro Name"
L["action/mleditbox/macrotext/att1tt"]			= "Enter the macrotext\nExample:|cffF95C25/cast Fireball|r"
L["action/mleditbox/item/att1tt"]				= "Enter the itemID or Item Name.\rItem IDs from Wowhead work best."
L["action/mlebActionTypeAtt2/l"]				= "Attribute2:"
L["action/mleditbox/spell/att2tt"]				= "Enter the spell ID or spell Name to cast.\nSpell IDs from Wowhead work best."
L["action/mleditbox/macro/att2tt"]				= "Leave blank for macros"
L["action/mleditbox/macrotext/att2tt"]			= "Leave blank for macrotext"
L["action/mleditbox/item/att2tt"]				= "Leave blank for items"
L["action/mleditbox/item/att2tt"]				= "Leave blank for items"
-- L["action/ebXOffset/l"]							= "X:"
-- L["action/ebXOffset/tt"]						= "Enter a numeric value to change the action X location relative to top left of the dna anchor\nHold Shift+Enter to change the value for all actions in this rotation"
-- L["action/ebYOffset/l"]							= "Y:"
-- L["action/ebYOffset/tt"]						= "Enter a numeric value to change the action Y location relative to top left of the dna anchor\nHold Shift+Enter to change the value for all actions in this rotation"
-- L["action/ebWidth/l"]							= "W:"
-- L["action/ebWidth/tt"]							= "Enter a numeric value to change the action width\nEnter 50% to change the action width to 50% of anchor width\nHold Shift+Enter to change the value for all actions in this rotation"
-- L["action/ebHeight/l"]							= "H:"
-- L["action/ebHeight/tt"]							= "Enter a numeric value to change the action height\nEnter 50% to change the action height to 50% of anchor height\nHold Shift+Enter to change the value for all actions in this rotation"
-- L["action/cbDisableButton/l"]					= "Disable"
-- L["action/cbDisableButton/tt"]					= "Check this box to disable this action in the rotation"
-- L["action/cbMouseEnableButton/l"]				= "Mouse"
-- L["action/cbMouseEnableButton/tt"]				= "Enable or disable mouse interaction for this action\nWarning: If player is in combat, the mouse interactivity cannot change until you leave combat\nHold Shift+Click to change mouse enabled for all actions in this rotation"
-- L["action/bActionKeybind/blizzard"]				= "Blizzard"
L["action/ilAMoveUp/tt"]						= "Move action up in the priority list"
L["action/ilAMoveDown/tt"]						= "Move action down in the priority list"
L["action/bActionDelete/tt"]					= "Delete this action\n|cffFF0000WARNING|r: No undo or prompt"
L["action/bCriteriaAdd/l"]						= "Add Criteria"
L["action/ebRenameAction/l"]					= "Rename Action:"
L["action/ebRenameAction/tt"]					= "Enter new action name and press ENTER"
L["action/mlebInfo/tt"]							= "Mouse over the debug box to pause the engine output\nMouse wheel to scroll up and down"
L["action/ilExportActionPack/tt"]				= "Click to create 1 line action pack\nShift+click to create script action pack\nAlt+click to create forum action pack"
L["action/cbInfo/tt"]							= "Click to display debug information about this action"
L["action/_dna_getactiontexture_status/e2"]	= "|cffFF0000Error|r Action type is not set"
L["action/_dna_getactiontexture_status/e3"]	= "|cffFF0000Error|r No texture found in dna.D.SpellInfo"
L["action/_dna_criteria_status/e1"]			= "|cffFF0000Error|r Pcall return="
L["action/_dna_criteria_status/i1"]			= "Info: Button is |cffFF0000DISABLED|r"
L["action/_dna_criteria_status/i2"]			= "Info: Button is a criteria group. Check calling action for pass or fail."
L["action/_dna_criteria_status/i3"]			= "Info: Button is disabled. No criteria to process."
L["action/_dna_criteria_status/fail"]			= "|cffFF0000FAIL|r"
L["action/_dna_criteria_status/pass"]			= "|cff00FF00PASS|r"
L["action/_dna_syntax_status/pass"]			= "|cff00FF00PASS|r"
L["action/_dna_syntax_status/e1"]				= "|cffFF0000Error|r"
L["action/bCriteriaTest/loadstringerror"]		= "Error: Syntax problem found in criteria text."
	
--*****************************************************
--Criteria
-- syntax is <parameter> for a required parameter
--*****************************************************
L["d/common/xoffset/l"]							= "X offset"
L["d/common/xoffset/tt"]						= "X offset from center of screen"
L["d/common/yoffset/l"]							= "Y offset"
L["d/common/yoffset/tt"]						= "Y offset from center of screen"

L["d/common/togglenumber/l"]					= "Toggle Number"
L["d/common/togglenumber/tt"]					= "Enter Toggle Number"

L["d/common/iconsize/l"]						= "Icon Size"
L["d/common/iconsize/tt"]						= "Enter Icon Size"

L["d/common/attribute/l"]						= "Attribute:"
L["d/common/attribute/tt"]						= "Enter the attribute name \n|cffF95C25baseticktime|r"
L["d/common/baseduration/l"]					= "Base Duration:"
L["d/common/baseduration/tt"]					= "Enter the spell base duration in seconds |cffF95C2590|r"
L["d/common/buff/l"]							= "Buff:"
L["d/common/buff/dv"]							= "Frost Armor"
L["d/common/buff/tt"]							= "Enter the buff name or id |cffF95C25Frost Armor, 7302|r"
L["d/common/buffid/l"]							= "Buff ID:"
L["d/common/buffid/dv"]							= "20217"
L["d/common/buffid/tt"]							= "Enter a numeric buff id |cffF95C2520217|r"
L["d/common/charges/l"]							= "Charges:"
L["d/common/charges/tt"]						= "Enter the number of charges |cffF95C252|r"
L["d/common/co/l"]								= "Comparison Operator:"
L["d/common/co/tt"]								= "Enter comparison operator |cffF95C25\n<\n>\n<=\n>=\n==\n~=|r"
L["d/common/cooldown/l"]						= "Cooldown:"
L["d/common/cooldown/tt"]						= "Enter the cooldown in seconds |cffF95C2515|r"
L["d/common/count/l"]							= "Count:"
L["d/common/count/tt"]							= "Enter a number"
L["d/common/combopoints/l"]						= "Combo Points:"
L["d/common/combopoints/tt"]					= "Enter the number of combopoints |cffF95C254|r"
L["d/common/debuff/l"]							= "Debuff:"
L["d/common/debuff/dv"]							= "Drunken Haze"
L["d/common/debuff/tt"]							= "Enter the buff name or id |cffF95C25Drunken Haze, 37591|r"
L["d/common/debuffid/l"]						= "Debuff ID:"
L["d/common/debuffid/dv"]						= "20217"
L["d/common/debuffid/tt"]						= "Enter a numeric debuff id |cffF95C2520217|r"
L["d/common/debufftype/l"]						= "Debuff Type:"
L["d/common/debufftype/dv"]						= "Poison"
L["d/common/debufftype/tt"]						= "Enter the debuff type:\n|cffF95C25Magic\nDisease\nPoison\nCurse|r"
L["d/common/di/l"]								= "Distance Index:"
L["d/common/di/tt"]								= "|cffF95C251|r=28 yards, |cffF95C252|r=11.11 yards, |cffF95C253|r=9.9 yards"
L["d/common/duration/l"]						= "Duration:"
L["d/common/duration/tt"]						= "Enter the duration in seconds |cffF95C254|r"
L["d/common/dy/l"]								= "Distance:"
L["d/common/dy/tt"]								= "Enter the number of yards\nExample: |cffF95C255|r"
L["d/common/eclipse/l"]							= "Eclipse:"
L["d/common/eclipse/tt"]						= "Enter the eclipse type\n|cffF95C25moon|r\n|cffF95C25sun|r\n|cffF95C25none|r"
L["d/common/energy/l"]							= "Energy:"
L["d/common/energy/tt"]							= "Enter the energy amount |cffF95C2556|r"
L["d/common/powerrequired/l"]					= "Power Required:"
L["d/common/powerrequired/tt"]					= "Enter the power amount required |cffF95C2556|r"
L["d/common/focus/l"]							= "Focus:"
L["d/common/focus/tt"]							= "Enter the focus amount |cffF95C2556|r"
L["d/common/gid/l"]								= "Global ID:"
L["d/common/gid/tt"]							= "Enter the spellid or itemid or macroid|r"
L["d/common/gs/l"]								= "Glyph Spell:"
L["d/common/gs/tt"]								= "Enter the glyph spellname or spellid inscribed into the socket\n|cffF95C25Glyph of Shred\n114234|r"
L["d/common/he/l"]								= "Health:"
L["d/common/he/tt"]								= "Enter health amount |cffF95C2515000|r"
L["d/common/item/l"]							= "Item:"
L["d/common/item/tt"]							= "Enter the itemID or itemName"
L["d/common/list/l"]							= "List:"
L["d/common/list/dv"]							= "Interrupts"
L["d/common/list/tt"]							= "Enter the list name |cffF95C25Interrupts|r"
L["d/common/number/l"]							= "Number:"
L["d/common/number/dv"]							= "10"
L["d/common/number/tt"]							= "Enter a number |cffF95C2510|r"
L["d/common/pe/l"]								= "Percentage:"
L["d/common/pe/tt"]								= "Enter percent without % sign Example:|cffF95C2575|r"
L["d/common/power/l"]							= "Power Type:"
L["d/common/power/tt"]							= "Enter powertype:|cffF95C25\nSPELL_POWER_MANA\nSPELL_POWER_RAGE\nSPELL_POWER_FOCUS\nSPELL_POWER_ENERGY\nSPELL_POWER_RUNES\nSPELL_POWER_RUNIC_POWER\nSPELL_POWER_SOUL_SHARDS\nSPELL_POWER_ASTRAL\nSPELL_POWER_HOLY_POWER\nSPELL_POWER_CHI\nSPELL_POWER_SHADOW_ORBS\nSPELL_POWER_BURNING_EMBERS\nSPELL_POWER_DEMONIC_FURY|r"
L["d/common/ppm/l"]								= "PPM:"
L["d/common/ppm/tt"]							= "Enter the procs per minute |cffF95C252.6|r"
L["d/common/seconds/l"]							= "Seconds:"
L["d/common/seconds/tt"]						= "Enter the number of seconds |cffF95C252.5|r"
L["d/common/slot/l"]							= "Slot:"
L["d/common/slot/tt"]							= "Enter the slot number |cffF95C251|r"
L["d/common/slotname/l"]						= "SlotName:"
L["d/common/slotname/tt"]						= "Enter slot name\n|cffF95C25\nHeadSlot\nNeckSlot\nShoulderSlot\nBackSlot\nChestSlot\nWristSlot\nHandsSlot\nWaistSlot\nLegsSlot\nFeetSlot\nFinger0Slot\nFinger1Slot\nTrinket0Slot\nTrinket1Slot\nMainHandSlot\nSecondaryHandSlot|r"

L["d/common/sp/l"]								= "Spell:"
L["d/common/sp/dv"]								= ""
L["d/common/sp/tt"]								= "Enter the spellname or spellid:\n|cffF95C25Brain Freeze\n57761|r"
L["d/common/iconsp/l"]							= "Icon Spell:"
L["d/common/iconsp/dv"]							= ""
L["d/common/iconsp/tt"]							= "Enter the spellname or spellid to use for the icon:\n|cffF95C25Brain Freeze\n57761|r"
L["d/common/spcdwatch/l"]						= "Spell CD to watch:"
L["d/common/spcdwatch/dv"]						= ""
L["d/common/spcdwatch/tt"]						= "Enter the spellname or spellid to watch for CD and toggle off:\n|cffF95C25Brain Freeze\n57761|r"
L["d/common/spellschool/l"]						= "Spell School:"
L["d/common/spellschool/tt"]					= "Enter a spell school number:\n|cffF95C251|r Physical\n|cffF95C252|r Holy\n|cffF95C253|r Fire\n|cffF95C254|r Nature\n|cffF95C255|r Frost\n|cffF95C256|r Shadow\n|cffF95C257|r Arcane"
L["d/common/stacks/l"]							= "Stacks:"
L["d/common/stacks/tt"]							= "Enter the number of stacks |cffF95C252|r"
L["d/common/ta"]								= "Talent:"
L["d/common/tadv"]								= "Shadow Focus"
L["d/common/tatt"]								= "Enter the talent name |cffF95C25Death Pact|r or talent ID |cffF95C2548743|r"
L["d/common/threatstatus/l"]					= "Threat Status"
L["d/common/threatstatus/dv"]					= "3"
L["d/common/threatstatus/tt"]					= "Enter the threat level:\n|cffF95C25-1|r unit is not on otherunit's threat table\n|cffF95C250|r not tanking, lower threat than tank\n|cffF95C251|r not tanking, higher threat than tank\n|cffF95C252|r insecurely tanking, another unit has higher threat but not tanking\n|cffF95C253|r securely tanking, highest threat"
L["d/common/ticks/l"]							= "Ticks:"
L["d/common/ticks/tt"]							= "Enter the number of Ticks |cffF95C2511|r"
L["d/common/ticktime/l"]						= "Tick Time:"
L["d/common/ticktime/tt"]						= "Enter the tick time in seconds |cffF95C2515|r"
L["d/common/truefalse/l"]						= "True/False:"
L["d/common/truefalse/tt"]						= "Enter |cffF95C25true|r or |cffF95C25false|r"
L["d/common/un/l"]								= "Unit:"
L["d/common/un/tt"]								= "Enter the unit name:\n|cffF95C25player\ntarget\npet\nraid10|r"
L["d/common/casterunit/l"]						= "Caster Unit:"
L["d/common/casterunit/tt"]						= "Enter the unit name:\n|cffF95C25player\ntarget\npet\nraid10|r\nLeave blank if you do not care who casted it."
L["d/common/aura/l"]							= "Aura:"
L["d/common/aura/dv"]							= ""
L["d/common/aura/tt"]							= "Enter the spellname or spellid:\n|cffF95C25Brain Freeze\n57761|r"
L["d/common/aurafilter/l"]						= "Aura Filter:"
L["d/common/aurafilter/dv"]						= "HELPFUL"
L["d/common/aurafilter/tt"]						= "Enter the Aura Filter:\n|cffF95C25HELPFUL|HARMFUL|PLAYER\|RAID|CANCELABLE|NOT_CANCELABLE|r"
L["d/common/valuename/l"]						= "Value Name:"
L["d/common/valuename/tt"]						= "Enter the value name:|cffF95C25\n_spellid\n"
L["d/common/value/l"]							= "Value:"
L["d/common/value/tt"]							= "Enter the value |cffF95C251234|r"
L["d/common/ws/l"]								= "Weapon Slot:"
L["d/common/ws/tt"]								= "Enter the weapon slot:\n|cffF95C25mainhand\noffhand\nthrown|r"
--PLAYER-----------------------------------------------
L["d/player"]									= "Player"
	L["d/player/GetPlayerCombatTime"]			= "Player in combat |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/player/GetPlayerDamageTaken"]			= "Player damage taken over last |cffF95C25<seconds>|r |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/player/GetPlayerEffectiveAttackPower"]	= "Player effective attack power is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/player/GetPlayerGCD"]					= "Player GCD is |cffF95C25<operator>|r |cffF95C25<seconds>|r"	
	L["d/player/GetPlayerHasAutoAttackOn"]		= "Player has Auto Attack on"
	L["d/player/GetPlayerHasGlyphSpellActive"]	= "Player has |cffF95C25<glyph spell>|r active"
	L["d/player/GetPlayerIsAutoCastingSpell"]	= "Player is autocasting |cffF95C25<spell>|r"
	L["d/player/GetPlayerIsSolo"]				= "Player is solo |cffF95C25<check LFG status>|r"
	L["d/player/GetPlayerKnowsSpell"]			= "Player knows |cffF95C25<spell>|r"
	L["d/player/GetPlayerPowerRegen"]			= "Player power regen is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/player/GetPlayerTimeToMaxPower"]		= "Player time to max power is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/player/GetPowerTimeToValue"]			= "Get time to |cffF95C25<power type>|r is |cffF95C25<required power>|r |cffF95C25<hiddenbool true|false>|r"
--PET-----------------------------------------------
L["d/pet"]										= "Pet"
	L["d/pet/GetPetSpellKnown"]					= "Pet |cffF95C25<spell>|r known"
	L["d/pet/GetPetSpellAutocasting"]			= "Pet autocasting |cffF95C25<spell>|r"
--UNIT-------------------------------------------------
L["d/unit"]										= "Unit"
	-- L["d/unit/GetHurtNPCCount"]					= "Hurt NPC count is |cffF95C25<operator>|r |cffF95C25<number>|r"
	-- L["d/unit/GetTargetTimeToDie"]				= "Target time to die is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
    L["d/unit/GetUnitAffectingCombat"]			= "|cffF95C25<unit>|r affecting combat"
	L["d/unit/GetUnitCastingInterruptibleSpell"]= "|cffF95C25<unit>|r casting interruptible spell"
	L["d/unit/GetUnitCastingDuration"]			= "|cffF95C25<unit>|r casting duration is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/unit/GetUnitCastingSpell"]				= "|cffF95C25<unit>|r casting |cffF95C25<spell>|r"
	L["d/unit/GetUnitCastingSpellInList"]		= "|cffF95C25<unit>|r casting spell in |cffF95C25<list>|r"
	L["d/unit/GetUnitCastPercent"]				= "|cffF95C25<unit>|r cast percent is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitCastTimeleft"]				= "|cffF95C25<unit>|r cast timeleft |cffF95C25<operator>|r |cffF95C25<number>|r seconds"
	L["d/unit/GetUnitDebuffTimeleftInList"]		= "|cffF95C25<unit>|r debuff timeleft in |cffF95C25<list>|r |cffF95C25<filter>|r"
	L["d/unit/GetUnitExists"]					= "|cffF95C25<unit>|r exists"
	L["d/unit/GetUnitHasBuffID"]				= "|cffF95C25<unit>|r has |cffF95C25<buffid>|r |cffF95C25<filter>|r"
	L["d/unit/GetUnitHasBuffIDStacks"]			= "|cffF95C25<unit>|r has |cffF95C25<buffid>|r |cffF95C25<filter>|r stacks |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitHasBuffName"]				= "|cffF95C25<unit>|r has |cffF95C25<buffname>|r |cffF95C25<filter>|r"
	L["d/unit/GetUnitHasBuffNameInList"]		= "|cffF95C25<unit>|r has buffname in |cffF95C25<list>|r"	
	L["d/unit/GetUnitHasBuffNameStacks"]		= "|cffF95C25<unit>|r has |cffF95C25<buffname>|r |cffF95C25<filter>|r stacks |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitHasBuffNameTimeleft"]		= "|cffF95C25<unit>|r has |cffF95C25<buffname>|r |cffF95C25<filter>|r timeleft |cffF95C25<operator>|r |cffF95C25<seconds>|r seconds"	
	L["d/unit/GetUnitHasDebuffID"]				= "|cffF95C25<unit>|r has |cffF95C25<debuffid>|r |cffF95C25<filter>|r"
	L["d/unit/GetUnitHasDebuffName"]			= "|cffF95C25<unit>|r has |cffF95C25<debuffname>|r |cffF95C25<filter>|r"
	L["d/unit/GetUnitHasDebuffNameInList"]		= "|cffF95C25<unit>|r has debuffname in |cffF95C25<list>|r"
	L["d/unit/GetUnitHasDebuffNameStacks"]		= "|cffF95C25<unit>|r has |cffF95C25<debuffname>|r |cffF95C25<filter>|r stacks |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitHasDebuffNameTimeleft"]	= "|cffF95C25<unit>|r has |cffF95C25<debuffname>|r |cffF95C25<filter>|r timeleft |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/unit/GetUnitHasDebuffType"]			= "|cffF95C25<unit>|r has |cffF95C25<debufftype>|r"
	L["d/unit/GetUnitHasMyBuffName"]			= "|cffF95C25<unit>|r has my |cffF95C25<buffname>|r"
	L["d/unit/GetUnitHasMyDebuffID"]			= "|cffF95C25<unit>|r has my |cffF95C25<debuffid>|r"
	L["d/unit/GetUnitHasMyDebuffName"]			= "|cffF95C25<unit>|r has my |cffF95C25<debuffname>|r"
	L["d/unit/GetUnitHasMyDebuffNameStacks"]	= "|cffF95C25<unit>|r has my |cffF95C25<debuffname>|r stacks |cffF95C25<operator>|r |cffF95C25<number>|r"	
	L["d/unit/GetUnitHasMyDebuffNameTimeleft"]	= "|cffF95C25<unit>|r has my |cffF95C25<debuffname>|r timeleft |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/unit/GetUnitHasMySpellTicksRemaining"]	= "|cffF95C25<unit>|r has |cffF95C25<spell>|r with |cffF95C25<baseticktime>|r ticks remaining"
	L["d/unit/GetUnitHealth"]					= "|cffF95C25<unit>|r health is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitHealthLost"]				= "|cffF95C25<unit>|r health lost is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitHealthPercent"]			= "|cffF95C25<unit>|r health percent is |cffF95C25<operator>|r |cffF95C25<number>|r"
    L["d/unit/GetUnitIsFriend"]					= "|cffF95C25<unit>|r is friends with |cffF95C25<otherunit>|r"
    L["d/unit/GetUnitIsEnemy"]					= "|cffF95C25<unit>|r is enemies with |cffF95C25<otherunit>|r"
    L["d/unit/GetUnitIsMoving"]					= "|cffF95C25<unit>|r is moving"
	L["d/unit/GetUnitIsPlayerControlled"]		= "|cffF95C25<unit>|r is player controlled"	
	L["d/unit/GetUnitIsUnit"]					= "|cffF95C25<unit>|r is |cffF95C25<unit>|r"
	L["d/unit/GetUnitLevel"]					= "|cffF95C25<unit>|r level is |cffF95C25<operator>|r |cffF95C25<number>|r"
    L["d/unit/GetUnitNeedsHeal"]                = "|cffF95C25<unit>|r needs heal |cffF95C25<heal@percent>|r or has |cffF95C25<debuffabsorblist>|r"
	L["d/unit/GetUnitNumberItemsEquippedInList"]= "|cffF95C25<unit>|r number of items equipped in |cffF95C25<list>|r is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitPower"]					= "|cffF95C25<unit>|r |cffF95C25<power type>|r |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitPowerDeficit"]				= "|cffF95C25<unit>|r |cffF95C25<power type>|r deficit is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitPowerMax"]					= "|cffF95C25<unit>|r max |cffF95C25<power type>|r |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitPowerPercent"]				= "|cffF95C25<unit>|r |cffF95C25<power type>|r percent is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/unit/GetUnitThreatSituation"]			= "|cffF95C25<unit>|r threat status on |cffF95C25<unit>|r is |cffF95C25<operator>|r |cffF95C25<threat status>|r"
--ITEM-------------------------------------------------
L["d/item"]										= "Item"
	L["d/item/GetItemCooldown"]					= "|cffF95C25<item>|r cooldown is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/item/GetItemCooldownLessThanGCD"]		= "|cffF95C25<item>|r cooldown is < global cooldown"
	L["d/item/GetItemCount"]					= "|cffF95C25<item>|r count is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/item/GetItemInRangeOfUnit"]			= "|cffF95C25<item>|r is in range of |cffF95C25<unit>|r"
	L["d/item/GetItemIsEquipped"]				= "|cffF95C25<item>|r is equipped"
	L["d/item/GetSlotCooldown"]					= "|cffF95C25<slot>|r cooldown is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/item/GetSlotCooldownLessThanGCD"]		= "|cffF95C25<slot>|r cooldown is < global cooldown"
--SPELL------------------------------------------------
L["d/spell"]									= "Spell"											
	L["d/spell/GetSpellAppliedAttackPower"]		= "|cffF95C25<spell>|r applied attack power on |cffF95C25<unit>|r"
	L["d/spell/GetSpellAppliedBonusDamage"]		= "|cffF95C25<spell>|r applied |cffF95C25<spellschool>|r bonus damage on |cffF95C25<unit>|r"
	L["d/spell/GetSpellAppliedBonusDPS"]		= "|cffF95C25<spell>|r |cffF95C25<spellschool>|r applied bonus DPS with |cffF95C25<base ticktime>|r on |cffF95C25<unit>|r"
	L["d/spell/GetSpellCurrentBonusDPS"]		= "|cffF95C25<spell>|r |cffF95C25<spellschool>|r current bonus DPS with |cffF95C25<base ticktime>|r"
	L["d/spell/GetSpellCastedComboPoints"]		= "|cffF95C25<spell>|r casted on |cffF95C25<unit>|r combo points"
	L["d/spell/GetSpellAppliedCritPercent"]		= "|cffF95C25<spell>|r applied |cffF95C25<spellschool>|r crit percent on |cffF95C25<unit>|r"
	L["d/spell/GetSpellAppliedDuration"]		= "|cffF95C25<spell>|r applied duration on |cffF95C25<unit>|r |cffF95C25<filter>|r is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/spell/GetSpellAppliedHastePercent"]	= "|cffF95C25<spell>|r applied haste percent on |cffF95C25<unit>|r"
	L["d/spell/GetSpellCastTime"]				= "|cffF95C25<spell>|r cast time is |cffF95C25<operator>|r |cffF95C25<number>|r seconds"
	L["d/spell/GetSpellCharges"]				= "|cffF95C25<spell>|r charges |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/spell/GetSpellChargeFractional"]		= "|cffF95C25<spell>|r charges fractional is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/spell/GetSpellChargesMax"]				= "|cffF95C25<spell>|r charges max is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/spell/GetSpellCooldown"]				= "|cffF95C25<spell>|r cooldown is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/spell/GetSpellCooldownLessThanGCD"]	= "|cffF95C25<spell>|r cooldown is < global cooldown"
	L["d/spell/GetSpellDamage"]					= "|cffF95C25<spell>|r damge is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/spell/GetSpellHaste"]					= "Get spell haste"
	L["d/spell/GetSpellInRangeOfUnit"]			= "|cffF95C25<spell>|r is in range of |cffF95C25<unit>|r"
	L["d/spell/GetSpellIsUsable"]				= "|cffF95C25<spell>|r is usable"
	L["d/spell/GetSpellLastCasted"]				= "|cffF95C25<spell>|r is my last casted spell"
	L["d/spell/GetSpellLastCastedElapsed"]		= "|cffF95C25<spell>|r elapsed time from last casted is |cffF95C25<operator>|r |cffF95C25<seconds>|r"	
	L["d/spell/GetSpellRechargeTimeRemaining"]	= "|cffF95C25<spell>|r recharge time remaining is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/spell/GetSpellAddTicksOnUnit"]			= "|cffF95C25<spell>|r ticks added to |cffF95C25<unit>|r with |cffF95C25<base duration>|r and |cffF95C25<base ticktime>|r"
	L["d/spell/GetSpellTickTimeOnUnit"]			= "|cffF95C25<spell>|r hasted tick time with |cffF95C25<base ticktime>|r on |cffF95C25<unit>|r"
	L["d/spell/GetSpellTotalTicksOnUnit"]		= "|cffF95C25<spell>|r total number of ticks with |cffF95C25<base ticktime>|r on |cffF95C25<unit>|r"
	L["d/spell/GetSpellTravelTime"]				= "|cffF95C25<spell>|r get travel time"
	L["d/spell/SetSpellInfo"]					= "Set |cffF95C25<spell>|r |cffF95C25<attribute>|r |cffF95C25<value>|r"
	L["d/spell/SetSpellTickTime"]				= "Set |cffF95C25<spell>|r |cffF95C25<ticktime>|r"
	L["d/spell/SetSpellTravelTime"]				= "Set |cffF95C25<startspell>|r |cffF95C25<endspell>|r travel time"
	
--CLASS------------------------------------------------
L["d/class"]									= "Class"
	--COMMON-------------------------------------------
	L["d/class/common/GetEnergy"]				= "Energy is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/common/GetEnergyRegenRate"]		= "Energy regen rate is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/common/GetEnergyTimeToMax"]					= "Time to max energy is |cffF95C25<operator>|r |cffF95C25<number>|r seconds"
	L["d/class/common/GetComboPoints"]						= "My combo points are |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/common/GetWeaponEnchant"]		= "My |cffF95C25<weaponslot>|r is enchanted with |cffF95C25<spell>|r"
	--DEATHKNIGHT--------------------------------------
	L["d/class/deathknight/rp"]					= "Runic Power:"
	L["d/class/deathknight/rptt"]				= "Enter the Runic Power amount |cffF95C2556|r"
	L["d/class/deathknight/GetDeathStrikeHealPercent"] = "Death Strike heal amount is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/deathknight/GetGhoulExists"]		= "Ghoul exists"
	L["d/class/deathknight/GetRunicPower"]		= "Runic Power is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/deathknight/depleated"]			= "Depleated Rune Count:"
	L["d/class/deathknight/depleatedtt"]		= "Enter the number of depleated runes |cffF95C252|r"
	L["d/class/deathknight/GetDeathRuneCount"]	= "Death Runes |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/deathknight/GetTotalDepletedRunes"]	= "Total Depleted Runes |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/deathknight/GetTotalRuneCount"]	= "Total Rune Count |cffF95C25<operator>|r |cffF95C25<number>|r"	
	--DRUID--------------------------------------------


	--HUNTER-------------------------------------------
	L["d/class/hunter/GetFocus"]				= "Focus is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/hunter/GetFocusDeficit"]			= "Focus deficit is |cffF95C25<operator>|r |cffF95C25<number>|r"
	
	--MAGE---------------------------------------------
	--MONK---------------------------------------------
	L["d/class/monk/GetChi"]					= "Chi is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/monk/GetStaggerPercent"]			= "Stagger percent is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/monk/GetStaggerTotal"]			= "Total stagger amount is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/monk/GetChi/l"]					= "Chi:"
	L["d/class/monk/GetChi/tt"]					= "Enter the chi amount |cffF95C253|r"
	L["d/class/monk/stagger/l"]					= "Stagger:"
	L["d/class/monk/stagger/dv"]				= "1000"
	L["d/class/monk/stagger/tt"]				= "Enter the stagger amount |cffF95C251000|r"
	L["d/class/monk/staggerpercent/l"]			= "Stagger Percent:"
	L["d/class/monk/staggerpercent/dv"]			= "10"
	L["d/class/monk/staggerpercent/tt"]			= "Enter the stagger percent amount |cffF95C2510|r"
	--PALADIN------------------------------------------
	L["d/class/paladin/GetHolyPower"]			= "I have |cffF95C25<operator>|r |cffF95C25<number>|r holy power"
	L["d/class/paladin/GetTimeToGainHolyPower"] = "Time to gain holy power is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	--PRIEST-------------------------------------------
	L["d/class/priest/GetShadowOrbs"]			= "I have |cffF95C25<operator>|r |cffF95C25<number>|r shadow orbs"
	--ROGUE--------------------------------------------
	L["d/class/rogue/GetComboPoints"]						= "Combo points are |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/rogue/GetComboPointDeficit"]						= "Combo point deficit is |cffF95C25<operator>|r |cffF95C25<number>|r"
	--SHAMAN-------------------------------------------
	L["d/class/shaman/totemslot/l"]						= "Totem Slot:"
	L["d/class/shaman/totemslot/tt"]						= "Enter the totem slot\n|cffF95C251|r Fire\n|cffF95C252|r Earth\n|cffF95C253|r Water\n|cffF95C254|r Air"
	L["d/class/shaman/totemspell/l"]						= "Totem Spell:"
	L["d/class/shaman/totemspell/tt"]					= "Enter the totem name or spellid.\n|cffF95C25Searing Totem\n|cffF95C253599|r"
	L["d/class/shaman/GetTotemSlotActive"]			= "Totem |cffF95C25<slot>|r is active"
	L["d/class/shaman/GetTotemSpellActive"]		= "Totem |cffF95C25<spell>|r is active"
	L["d/class/shaman/GetTotemSlotTimeLeft"]		= "Totem |cffF95C25<slot>|r has |cffF95C25<operator>|r |cffF95C25<seconds>|r remaining"
	
	--WARLOCK------------------------------------------
	L["d/class/warlock/GetBurningEmbers"]			= "Burning Embers |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/warlock/burningembers/tt"]				= "Enter the number of Burning Embers |cffF95C252|r"
	L["d/class/warlock/burningembers/l"]				= "Burning Embers:"
	L["d/class/warlock/GetBurningEmbersSegs"]	= "Burning Ember segments |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/warlock/burningemberss/tt"]			= "Enter the number of Burning Ember segments |cffF95C250-40|r"
	L["d/class/warlock/burningemberss/l"]				= "Burning Ember Segments:"
	L["d/class/warlock/GetDemonicFury"]				= "Demonic Fury |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/warlock/df/tt"]								= "Enter the amount of Demonic Fury |cffF95C252|r"
	L["d/class/warlock/df/l"]									= "Demonic Fury:"
	L["d/class/warlock/GetSecondsInMetamorphosis"]= "Seconds in Metamorphosis |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/class/warlock/GetSoulShards"]					= "Soul Shards |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/warlock/soulshards/tt"]					= "Enter the number of Soul Shards |cffF95C252|r"
	L["d/class/warlock/soulshards/l"]						= "Soul Shards:"
	--WARRIOR------------------------------------------
	L["d/class/warrior/GetRage"]							= "My rage is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/class/warrior/rage/l"]								= "Rage:"
	L["d/class/warrior/rage/tt"]								= "Enter the amount of rage |cffF95C25110|r"
--TALENTS----------------------------------------------
L["d/talents"]														= "Talents"
	L["d/talents/GetTalentEnabled"]						= "Player has |cffF95C25<talent name>|r enabled"
--MISC-------------------------------------------------
L["d/misc"]														= "Misc"
	L["d/misc/an/l"]												= "Action Name:"
	L["d/misc/an/tt"]											= "Enter the action name\nEx:|cffF95C25Fireball|r"
	L["d/misc/GetActionCriteriaState"]					= "Get |cffF95C25<action name>|r criteria state"
	L["d/misc/GetActionDisabled"]							= "|cffF95C25<action name>|r is disabled"
	L["d/misc/GetActionTimeUntilNeeded"]				= "Get |cffF95C25<action name>|r time until needed"
	L["d/misc/ActionDisableAnotherAction"]			= "Make this action toggle disable on |cffF95C25<action name>|r"
	L["d/misc/GetToggleEnabled"]				= "Get toggle |cffF95C25<toggle #>|r enabled\n Macro: |cffF95C25/run dna.ToggleNumber(1)|r"
	L["d/misc/EnableLua"]						= "Enable lua in the criteria for this action"
	L["d/misc/SetActionValue"]					= "Set action |cffF95C25<valuename>|r to |cffF95C25<value>|r"
	L["d/misc/SetWeakAuraInfo"]						= "Set WeakAuras info to |cffF95C25<keybind> <spellname>|r"
	L["d/misc/keybind/l"]						= "Key:"
	L["d/misc/keybind/dv"]					= "2"
	L["d/misc/keybind/tt"]					= "Enter key bind for the action: \n|cffF95C252|r"
	L["d/misc/holdkey/l"]						= "Hold the key down?"
	L["d/misc/holdkey/dv"]						= "false"

--GROUP-------------------------------------------------
L["d/group"]									= "Group"
	L["d/group/GetHealableLowestHealthPercent"]	= "Lowest health percent group member within |cffF95C25<spell>|r range is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/group/GetNumberOfGroupMembersWithCurableDebuffType"]	= "Number of group members with curable |cffF95C25<debufftype>|r is |cffF95C25<operator>|r |cffF95C25<number>|r"	
	L["d/group/GetNumHurtPlayers"]				= "Number of hurt group members |cffF95C25<minhurtpercent>|r |cffF95C25<distindex>|r is |cffF95C25<operator>|r |cffF95C25<number>|r"		
	L["d/group/GetTotalHealthLoss"]				= "Total raid health lost |cffF95C25<maxhealthlossperunit>|r is |cffF95C25<operator>|r |cffF95C25<totalhealthloss>|r"
	L["d/group/GetTotalHealthLossWithMyBuffName"]	= "Total raid health lost with my |cffF95C25<buffname>|r is |cffF95C25<operator>|r |cffF95C25<totalhealthloss>|r |cffF95C25<maxhealthlossperunit>|r"
	L["d/group/GetSpellOldestRaidBuffNameDuration"]	= "My oldest tracked |cffF95C25<spell>|r buff or debuff duration is |cffF95C25<operator>|r |cffF95C25<seconds>|r"
	L["d/group/GetSpellNumberOfGroupMembersApplied"] = "Number of group members with my |cffF95C25<buffname>|r applied is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/group/GetNumberOfGroupMembersMissingBuff"] = "Number of group members missing |cffF95C25<buffname>|r is |cffF95C25<operator>|r |cffF95C25<number>|r"
	L["d/group/GetSpellNumberOfUnitsApplied"]	= "|cffF95C25<spell>|r is applied on |cffF95C25<operator>|r |cffF95C25<number>|r of units"



